# Generated by Django 2.2.12 on 2021-04-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='fname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='lname',
            field=models.CharField(max_length=50),
        ),
    ]
